name: "Build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfield:cpp17_root-v6-26-06_geant4-v11.0.3_garfield-eb1b5403
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: CMake configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: CMake build
        run: |
          cmake --build build
